# Generated by Django 3.2.7 on 2021-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
                ('about', models.CharField(max_length=150)),
            ],
        ),
    ]
