# Generated by Django 3.2.7 on 2021-09-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bookimage',
            field=models.ImageField(blank=True, null=True, upload_to='Books'),
        ),
    ]
